import { Router, type IRouter } from "express";
import healthRouter from "./health";
import companiesRouter from "./companies";
import usersRouter from "./users";
import adminUsersRouter from "./adminUsers";
import dashboardRouter from "./dashboard";
import projectsRouter from "./projects";
import timeEntriesRouter from "./timeEntries";
import deliverablesRouter from "./deliverables";
import milestonesRouter from "./milestones";
import todosRouter from "./todos";
import offersRouter from "./offers";
import contractsRouter from "./contracts";
import invoicesRouter from "./invoices";
import messagesRouter from "./messages";
import notificationsRouter from "./notifications";
import complianceRouter from "./compliance";
import adminDashboardRouter from "./adminDashboard";
import auditLogsRouter from "./auditLogs";
import reportsRouter from "./reports";
import expensesRouter from "./expenses";

const router: IRouter = Router();

router.use(healthRouter);
router.use(companiesRouter);
router.use(usersRouter);
router.use(adminUsersRouter);
router.use(dashboardRouter);
router.use(adminDashboardRouter);
router.use(projectsRouter);
router.use(timeEntriesRouter);
router.use(deliverablesRouter);
router.use(milestonesRouter);
router.use(todosRouter);
router.use(offersRouter);
router.use(contractsRouter);
router.use(invoicesRouter);
router.use(messagesRouter);
router.use(notificationsRouter);
router.use(complianceRouter);
router.use(auditLogsRouter);
router.use(reportsRouter);
router.use(expensesRouter);

export default router;
